// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQMcCbqKOX3SNWlPJOQSauAWKk4dErjUE',
    appId: '1:15983001402:web:fa80e34d76f4790513da03',
    messagingSenderId: '15983001402',
    projectId: 'vize030120100',
    authDomain: 'vize030120100.firebaseapp.com',
    storageBucket: 'vize030120100.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCglU-lnajsOWXCy_Zc64fZafekmIIgQc8',
    appId: '1:15983001402:android:24669f0d28f5f8a013da03',
    messagingSenderId: '15983001402',
    projectId: 'vize030120100',
    storageBucket: 'vize030120100.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjiOPTO2-GBCa9EZzGhNpOJDLGkd4Q6rA',
    appId: '1:15983001402:ios:f2087da398c3a91d13da03',
    messagingSenderId: '15983001402',
    projectId: 'vize030120100',
    storageBucket: 'vize030120100.appspot.com',
    iosClientId: '15983001402-dmchrn7mn3fas2rhh1k69449cmmp8vu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjiOPTO2-GBCa9EZzGhNpOJDLGkd4Q6rA',
    appId: '1:15983001402:ios:f2087da398c3a91d13da03',
    messagingSenderId: '15983001402',
    projectId: 'vize030120100',
    storageBucket: 'vize030120100.appspot.com',
    iosClientId: '15983001402-dmchrn7mn3fas2rhh1k69449cmmp8vu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
